-
  name: Install Softwares
  hosts: all
  vars:
    packages:
      - name: nginx
        required: True
      - name: apache
        required: False
      - name: mysql
        required: True
  tasks:
    - name: "Install {{item.name}} on Debian"
      apt:
        name: "{{item.name}}"
        state: present

      loop: "{{packages}}"
