-
  name: Create users on web
  hosts: web
  become: yes
  tasks:
    - name: Creat users
      user:
        name: '{{item}}'
        state: present
      loop:
      - khabib
      - arman
      - lucille
      - joshua
      - kurduk
      - hypuclam
      - momo
      - appa
